
export const SET_COUNTRY = 'SET_COUNTRY';
export const GET_COUNTRY = 'GET_COUNTRY';
export const REVEIVING_DETAILS = 'MAKE REVEIVING_DETAILS';
export const RECEIEVED_DETAILS = 'MAKE RECEIEVED_DETAILS';